#!/usr/bin/env sh
if command -v gitleaks >/dev/null 2>&1; then
  gitleaks detect --source . --redact || { echo "gitleaks failed"; exit 1; }
else
  echo "gitleaks not found, skipping"
fi
npx prettier -c . || exit 1
npx eslint . || true
exit 0
